In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/mail_data.csv")

In [ ]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [ ]:
df.shape

(5572, 2)

In [ ]:
df.loc[df['Category'] == 'spam', 'Category',] = 0
df.loc[df['Category'] == 'ham', 'Category',] = 1

In [ ]:
df

     Category                                            Message
0           1  Go until jurong point, crazy.. Available only ...
1           1                      Ok lar... Joking wif u oni...
2           0  Free entry in 2 a wkly comp to win FA Cup fina...
3           1  U dun say so early hor... U c already then say...
4           1  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567        0  This is the 2nd time we have tried 2 contact u...
5568        1               Will ü b going to esplanade fr home?
5569        1  Pity, * was in mood for that. So...any other s...
5570        1  The guy did some bitching but I acted like i'd...
5571        1                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
X = df['Message']
y = df['Category']

In [ ]:
X.head(2)

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
Name: Message, dtype: object

In [ ]:
y.head(2)

0    1
1    1
Name: Category, dtype: object

In [ ]:
# split the dataset into 80 and 20
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
X_train.head()

1114    No I'm good for the movie, is it ok if I leave...
3589    If you were/are free i can give. Otherwise nal...
3095    Have you emigrated or something? Ok maybe 5.30...
1012          I just got home babe, are you still awake ?
3320                      Kay... Since we are out already
Name: Message, dtype: object

In [ ]:
y_train.head()

1114    ham
3589    ham
3095    ham
1012    ham
3320    ham
Name: Category, dtype: object

In [ ]:
X_test.head()

4456    Storming msg: Wen u lift d phne, u say "HELLO"...
690     <Forwarded from 448712404000>Please CALL 08712...
944     And also I've sorta blown him off a couple tim...
3768                  Sir Goodmorning, Once free call me.
1189    All will come alive.better correct any good lo...
Name: Message, dtype: object

In [ ]:
  y_test.head()

4456     ham
690     spam
944      ham
3768     ham
1189     ham
Name: Category, dtype: object

In [ ]:

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [ ]:
model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', MultinomialNB())
])

In [ ]:
model.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [ ]:
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9596412556053812

In [ ]:
def predict_spam(message):
    prediction = model.predict([message])[0]
    return "Spam" if prediction == "spam" else "Not Spam"

In [ ]:
%%capture
pip install gradio

In [ ]:
import gradio as gr

with gr.Blocks(theme=gr.themes.Soft(primary_hue="red", secondary_hue="blue")) :
    gr.Markdown(
        """
        # 📧 Spam Email Detector
        Detect whether an email message is **Spam or Not Spam**.
        Built with **Naive Bayes + TF-IDF** 🔥
        """
    )

    with gr.Row():
        with gr.Column(scale=2):
            input_box = gr.Textbox(
                label="✍️ Enter your email message",
                placeholder="Type or paste an email message here...",
                lines=6
            )
            predict_btn = gr.Button("🔍 Check Spam", variant="primary")

        with gr.Column(scale=1):
            output_label = gr.Label(label="Prediction Result")

    predict_btn.click(fn=predict_spam, inputs=input_box, outputs=output_label)

# Launch app
demo.launch(share=True)

Rerunning server... use `close()` to stop if you need to change `launch()` parameters.
----
Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://da6bd967ee533fc154.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)